# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: in_toto_attestation/v1/statement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from in_toto_attestation.v1 import resource_descriptor_pb2 as in__toto__attestation_dot_v1_dot_resource__descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&in_toto_attestation/v1/statement.proto\x12\x16in_toto_attestation.v1\x1a\x19google/protobuf/any.proto\x1a\x30in_toto_attestation/v1/resource_descriptor.proto\"\x9d\x01\n\tStatement\x12\x13\n\x04type\x18\x01 \x01(\tR\x05_type\x12;\n\x07subject\x18\x02 \x03(\x0b\x32*.in_toto_attestation.v1.ResourceDescriptor\x12\x15\n\rpredicateType\x18\x03 \x01(\t\x12\'\n\tpredicate\x18\x04 \x01(\x0b\x32\x14.google.protobuf.AnyBR\n\x1fio.github.intoto.attestation.v1Z/github.com/adityasaky/in-toto-attestation/go/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'in_toto_attestation.v1.statement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037io.github.intoto.attestation.v1Z/github.com/adityasaky/in-toto-attestation/go/v1'
  _STATEMENT._serialized_start=144
  _STATEMENT._serialized_end=301
# @@protoc_insertion_point(module_scope)
